### ISSUE TITLE
Trained model's availability

### ISSUE THREAD

**Issue by Sid2697** [hbdat/eccv20_Multi_Task_Procedure_Learning#1]
Hello, thank you for providing the implementation of your paper! I was trying to replicate the results in the paper. Will it be possible for you to share the models trained for this work?

**Comment by hbdat** [comment]
Hi @Sid2697 ,

Thanks for your interest in the project.
I have uploaded the pretrained model for multi-task settings (K=15) in both CrossTask and ProceL under the following link:
https://drive.google.com/drive/folders/1O8YnICuaQS6gwblu5PwuLMxnES1JBdsV?usp=sharing

Best, 
Dat

**Comment by Sid2697** [comment]
Hey @hbdat, thanks a lot for sharing the models! These will help a lot. Also, while navigating through the code, I found a couple of places where the README was sightly inaccurate, do you mind if I create a pull request for correcting the same?

**Comment by hbdat** [comment]
Hi @Sid2697 ,

Sure, I would really appreciate it.

Best,
Dat
