### ISSUE TITLE
raw_data_dir not present in global_setting

### ISSUE THREAD

**Issue by Sid2697** [hbdat/eccv20_Multi_Task_Procedure_Learning#3]
Hey!

The script `FeatureVGGDataset.py` imports and uses `raw_data_dir` from `global_setting`. However, `raw_data_dir` variable is not declared in `global_setting`.

For my purpose, I was able to run the code by setting `raw_data_dir` to `None` in `global_setting`. However, I guess, we should add a condition in `FeatureVGGDataset.py` at line 41 https://github.com/hbdat/eccv20_Multi_Task_Procedure_Learning/blob/7783e7b9b47498933d359adfd761579f09934c3c/core/FeatureVGGDataset.py#L41 for avoiding the error when we do not want to visualise the dataset.

Regards,
Siddhant Bansal

**Comment by hbdat** [comment]
Hi @Sid2697 ,

Thanks a lot for raising the issue. 
I will add a condition like you suggest to avoid this error.

Sorry for my late response, somehow the notifications got lost in my mailbox.

Best,
Dat

**Comment by Sid2697** [comment]
> Thanks a lot for raising the issue.
> I will add a condition like you suggest to avoid this error.

That will be great, thanks!

> Sorry for my late response, somehow the notifications got lost in my mailbox.

That is completely fine! Can you please have a look at the issue #5?

**Comment by hbdat** [comment]
I have uploaded the internal .mat file which should fix #5 (please prefer to my answer for more details).

Best,
Dat

**Comment by Sid2697** [comment]
Thanks a lot for sharing the annotations!

Do you want me to create a PR for this issue?

**Comment by hbdat** [comment]
Sure.
I would appreciate that.
Thanks @Sid2697 .
