### ISSUE TITLE
full copy of videos

### ISSUE THREAD

**Issue by huguyuehuhu** [hbdat/eccv20_Multi_Task_Procedure_Learning#7]
Hi, since some videos of Procel Dataset are missing or private now, shall you share a  full copy of this dataset? Thanks.

**Comment by hbdat** [comment]
Hi @huguyuehuhu ,

Sorry for the late response.
Here is the link to download all videos in the dataset.
https://drive.google.com/file/d/1WDzUiT_8_uW0PaYdzdcJYMTCFc8o-0Bu/view

Best,
Dat

**Comment by huguyuehuhu** [comment]
Thank you very much for sharing.
